### PR TITLE
Update depends.

### PR DESCRIPTION
**Pull request by envygeeks**
content-pipeline 1.0.0 (a move to semver for content-pipeline), the rest are standard updates.

### CODE REVIEW

**Comment by jipiboily** [comment]
Looking good, but I did not test it. Did you test it yourself? If yes, over what version of Monologue?

Thanks!

**Comment by envygeeks** [comment]
@jipiboily I assumed there was no need for any testing as the API remained exactly the same on the external face with only there being a bit of minor cleanup to the code and adjustments to internals that made the API a bit more fluid (in that I started moving some {} opts into defaulting to {} instead of nil).  The spec did not change at all but went through some organization to for the next version which will add some extra features but will not affect the legacy API.

**Comment by envygeeks** [comment]
Really the only thing that release did was push me towards SemVer, it was just an aesthetic release.

**Comment by jipiboily** [comment]
Awesome thanks, thanks a lot @envygeeks!

**Pull request merged**
